<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Etablissement;
use App\Models\Ville;
use App\Models\Categorie;
use App\Models\User;
use Illuminate\Support\Str;

class EtablissementSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $villes = Ville::all()->keyBy('slug');
        $categories = Categorie::all()->keyBy('slug');
        $adminUser = User::where('email', 'admin@bonnesadresses.bj')->first();

        $etablissementsData = [
            // Cotonou - Hôtels
            [
                'nom' => 'Bénin Royal Hôtel',
                'ville_slug' => 'cotonou',
                'categorie_slug' => 'hotels',
                'description' => 'Un hôtel de luxe offrant des services de qualité supérieure.',
                'adresse' => 'Lot 398, Quartier Maro Militaire, Cotonou',
                'telephone' => '+229 21 30 12 34',
                'whatsapp' => '+229 97 00 00 00',
                'email' => 'contact@beninroyalhotel.com',
                'site_web' => 'https://www.beninroyalhotel.com',
                'latitude' => 6.366667,
                'longitude' => 2.416667,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '50000 - 150000 FCFA',
                'photo_principale' => 'https://files.manuscdn.com/user_upload_by_module/session_file/310519663531040389/JmgFoSsLPXMMdrGd.jpg',
                'statut' => 'actif',
                'en_vedette' => true,
                'services' => ['Wifi', 'Piscine', 'Restaurant', 'Parking']
            ],
            [
                'nom' => 'Golden Tulip Le Diplomate',
                'ville_slug' => 'cotonou',
                'categorie_slug' => 'hotels',
                'description' => 'Hôtel moderne avec vue sur la mer et toutes les commodités.',
                'adresse' => 'Boulevard de la Marina, Cotonou',
                'telephone' => '+229 21 30 12 35',
                'whatsapp' => '+229 97 00 00 01',
                'email' => 'contact@goldentulip.com',
                'site_web' => 'https://diplomate-cotonou.goldentulip.com',
                'latitude' => 6.350000,
                'longitude' => 2.433333,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '75000 - 200000 FCFA',
                'photo_principale' => 'https://files.manuscdn.com/user_upload_by_module/session_file/310519663531040389/jvNFkZbvSSpRzJbe.jpg',
                'statut' => 'actif',
                'en_vedette' => true,
                'services' => ['Wifi', 'Piscine', 'Salle de sport', 'Restaurant', 'Bar']
            ],
            [
                'nom' => 'Novotel Cotonou Orisha',
                'ville_slug' => 'cotonou',
                'categorie_slug' => 'hotels',
                'description' => 'Un cadre agréable pour les affaires et les loisirs.',
                'adresse' => 'Boulevard de la Marina, Cotonou',
                'telephone' => '+229 21 30 12 36',
                'whatsapp' => '+229 97 00 00 02',
                'email' => 'contact@novotel.com',
                'site_web' => 'https://www.novotel.com',
                'latitude' => 6.351000,
                'longitude' => 2.434000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '60000 - 180000 FCFA',
                'photo_principale' => 'https://files.manuscdn.com/user_upload_by_module/session_file/310519663531040389/snMDtYPJGqtnZuuu.jpg',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Wifi', 'Piscine', 'Restaurant', 'Parking']
            ],
            [
                'nom' => 'Maison Rouge Cotonou',
                'ville_slug' => 'cotonou',
                'categorie_slug' => 'hotels',
                'description' => 'Hôtel charmant avec une ambiance chaleureuse.',
                'adresse' => 'Quartier Les Cocotiers, Cotonou',
                'telephone' => '+229 21 30 12 37',
                'whatsapp' => '+229 97 00 00 03',
                'email' => 'contact@maisonrouge.com',
                'site_web' => 'https://www.maisonrouge.com',
                'latitude' => 6.370000,
                'longitude' => 2.400000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '40000 - 100000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Maison+Rouge+Cotonou',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Wifi', 'Climatisation', 'Petit déjeuner']
            ],
            [
                'nom' => 'Azalaï Hotel Cotonou',
                'ville_slug' => 'cotonou',
                'categorie_slug' => 'hotels',
                'description' => 'Un hôtel de référence pour les séjours d\affaires et de loisirs.',
                'adresse' => 'Quartier Ganhi, Cotonou',
                'telephone' => '+229 21 30 12 38',
                'whatsapp' => '+229 97 00 00 04',
                'email' => 'contact@azalai.com',
                'site_web' => 'https://www.azalai.com',
                'latitude' => 6.360000,
                'longitude' => 2.420000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '80000 - 250000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Azalai+Hotel+Cotonou',
                'statut' => 'actif',
                'en_vedette' => true,
                'services' => ['Wifi', 'Piscine', 'Restaurant', 'Salle de conférence']
            ],
            [
                'nom' => 'Sofitel Cotonou Marina Hotel & Spa',
                'ville_slug' => 'cotonou',
                'categorie_slug' => 'hotels',
                'description' => 'Luxe et confort au bord de l\océan.',
                'adresse' => 'Boulevard de la Marina, Cotonou',
                'telephone' => '+229 21 30 12 39',
                'whatsapp' => '+229 97 00 00 05',
                'email' => 'contact@sofitel.com',
                'site_web' => 'https://www.sofitel.com',
                'latitude' => 6.349000,
                'longitude' => 2.435000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '100000 - 300000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Sofitel+Cotonou',
                'statut' => 'actif',
                'en_vedette' => true,
                'services' => ['Spa', 'Piscine', 'Restaurant gastronomique', 'Accès plage']
            ],
            [
                'nom' => 'Nobila Airport Hotel',
                'ville_slug' => 'cotonou',
                'categorie_slug' => 'hotels',
                'description' => 'Idéalement situé près de l\aéroport pour vos transits.',
                'adresse' => 'Quartier Cadjehoun, Cotonou',
                'telephone' => '+229 21 30 12 40',
                'whatsapp' => '+229 97 00 00 06',
                'email' => 'contact@nobila.com',
                'site_web' => 'https://www.nobila.com',
                'latitude' => 6.355000,
                'longitude' => 2.380000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '45000 - 120000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Nobila+Airport+Hotel',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Navette aéroport', 'Wifi', 'Restaurant']
            ],
            [
                'nom' => 'Hotel Du Lac',
                'ville_slug' => 'cotonou',
                'categorie_slug' => 'hotels',
                'description' => 'Un havre de paix au bord du lac Nokoué.',
                'adresse' => 'Akpakpa, Cotonou',
                'telephone' => '+229 21 30 12 41',
                'whatsapp' => '+229 97 00 00 07',
                'email' => 'contact@hoteldulac.com',
                'site_web' => 'https://www.hoteldulac.com',
                'latitude' => 6.375000,
                'longitude' => 2.450000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '35000 - 90000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Hotel+Du+Lac',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Vue sur lac', 'Restaurant', 'Bar']
            ],
            [
                'nom' => 'Ibis Cotonou',
                'ville_slug' => 'cotonou',
                'categorie_slug' => 'hotels',
                'description' => 'Hôtel économique et confortable en plein cœur de Cotonou.',
                'adresse' => 'Boulevard de la Marina, Cotonou',
                'telephone' => '+229 21 30 12 42',
                'whatsapp' => '+229 97 00 00 08',
                'email' => 'contact@ibis.com',
                'site_web' => 'https://www.ibis.com',
                'latitude' => 6.352000,
                'longitude' => 2.432000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '30000 - 70000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Ibis+Cotonou',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Wifi', 'Restaurant', 'Climatisation']
            ],
            [
                'nom' => 'Beach Sand Hotel',
                'ville_slug' => 'cotonou',
                'categorie_slug' => 'hotels',
                'description' => 'Profitez de la plage et du soleil dans cet hôtel convivial.',
                'adresse' => 'Route des Pêches, Cotonou',
                'telephone' => '+229 21 30 12 43',
                'whatsapp' => '+229 97 00 00 09',
                'email' => 'contact@beachsandhotel.com',
                'site_web' => 'https://www.beachsandhotel.com',
                'latitude' => 6.330000,
                'longitude' => 2.350000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '40000 - 100000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Beach+Sand+Hotel',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Accès plage', 'Piscine', 'Restaurant']
            ],

            // Cotonou - Restaurants
            [
                'nom' => 'Face À La Mer',
                'ville_slug' => 'cotonou',
                'categorie_slug' => 'restaurants',
                'description' => 'Restaurant en bord de mer avec une cuisine exquise.',
                'adresse' => 'Fidjrossé, Cotonou',
                'telephone' => '+229 21 30 12 44',
                'whatsapp' => '+229 97 00 00 10',
                'email' => 'contact@facealamer.com',
                'site_web' => 'https://www.facealamer.com',
                'latitude' => 6.335000,
                'longitude' => 2.360000,
                'horaires' => json_encode(['Lundi-Dimanche' => '12h-23h']),
                'fourchette_prix' => '10000 - 30000 FCFA',
                'photo_principale' => 'https://files.manuscdn.com/user_upload_by_module/session_file/310519663531040389/kECVwASNaWmFTxvU.jpg',
                'statut' => 'actif',
                'en_vedette' => true,
                'services' => ['Vue sur mer', 'Terrasse', 'Cuisine locale et internationale']
            ],
            [
                'nom' => 'Jaaba - Grill & Bar',
                'ville_slug' => 'cotonou',
                'categorie_slug' => 'restaurants',
                'description' => 'Spécialités grillades et ambiance décontractée.',
                'adresse' => 'Haie Vive, Cotonou',
                'telephone' => '+229 21 30 12 45',
                'whatsapp' => '+229 97 00 00 11',
                'email' => 'contact@jaaba.com',
                'site_web' => 'https://www.jaaba.com',
                'latitude' => 6.380000,
                'longitude' => 2.405000,
                'horaires' => json_encode(['Mardi-Dimanche' => '18h-00h']),
                'fourchette_prix' => '8000 - 25000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Jaaba+Grill+Bar',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Grillades', 'Bar', 'Musique live']
            ],
            [
                'nom' => 'La Cabane du Pêcheur',
                'ville_slug' => 'cotonou',
                'categorie_slug' => 'restaurants',
                'description' => 'Poissons frais et fruits de mer dans un cadre authentique.',
                'adresse' => 'Fidjrossé, Cotonou',
                'telephone' => '+229 21 30 12 46',
                'whatsapp' => '+229 97 00 00 12',
                'email' => 'contact@cabanedupecheur.com',
                'site_web' => 'https://www.cabanedupecheur.com',
                'latitude' => 6.336000,
                'longitude' => 2.361000,
                'horaires' => json_encode(['Mercredi-Lundi' => '11h-22h']),
                'fourchette_prix' => '12000 - 35000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Cabane+Pecheur',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Fruits de mer', 'Vue sur mer', 'Ambiance locale']
            ],
            [
                'nom' => 'Le Privé',
                'ville_slug' => 'cotonou',
                'categorie_slug' => 'restaurants',
                'description' => 'Restaurant gastronomique pour une expérience culinaire unique.',
                'adresse' => 'Quartier Les Cocotiers, Cotonou',
                'telephone' => '+229 21 30 12 47',
                'whatsapp' => '+229 97 00 00 13',
                'email' => 'contact@leprive.com',
                'site_web' => 'https://www.leprive.com',
                'latitude' => 6.371000,
                'longitude' => 2.401000,
                'horaires' => json_encode(['Mardi-Samedi' => '19h-23h']),
                'fourchette_prix' => '20000 - 50000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Le+Prive',
                'statut' => 'actif',
                'en_vedette' => true,
                'services' => ['Cuisine française', 'Vins fins', 'Cadre élégant']
            ],
            [
                'nom' => 'L\Imprévu',
                'ville_slug' => 'cotonou',
                'categorie_slug' => 'restaurants',
                'description' => 'Cuisine inventive et ambiance cosy.',
                'adresse' => 'Haie Vive, Cotonou',
                'telephone' => '+229 21 30 12 48',
                'whatsapp' => '+229 97 00 00 14',
                'email' => 'contact@limprevu.com',
                'site_web' => 'https://www.limprevu.com',
                'latitude' => 6.381000,
                'longitude' => 2.406000,
                'horaires' => json_encode(['Lundi-Samedi' => '12h-14h30, 19h-22h30']),
                'fourchette_prix' => '15000 - 40000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=LImprevu',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Cuisine fusion', 'Terrasse', 'Cocktails']
            ],
            [
                'nom' => 'Le Berlin',
                'ville_slug' => 'cotonou',
                'categorie_slug' => 'restaurants',
                'description' => 'Spécialités africaines et européennes dans un cadre moderne.',
                'adresse' => 'Quartier Zongo, Cotonou',
                'telephone' => '+229 21 30 12 49',
                'whatsapp' => '+229 97 00 00 15',
                'email' => 'contact@leberlin.com',
                'site_web' => 'https://www.leberlin.com',
                'latitude' => 6.365000,
                'longitude' => 2.425000,
                'horaires' => json_encode(['Lundi-Dimanche' => '10h-23h']),
                'fourchette_prix' => '7000 - 20000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Le+Berlin',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Cuisine africaine', 'Cuisine européenne', 'Bar']
            ],
            [
                'nom' => 'Villa Kaya',
                'ville_slug' => 'cotonou',
                'categorie_slug' => 'restaurants',
                'description' => 'Restaurant et lounge avec une ambiance chic.',
                'adresse' => 'Haie Vive, Cotonou',
                'telephone' => '+229 21 30 12 50',
                'whatsapp' => '+229 97 00 00 16',
                'email' => 'contact@villakaya.com',
                'site_web' => 'https://www.villakaya.com',
                'latitude' => 6.382000,
                'longitude' => 2.407000,
                'horaires' => json_encode(['Mardi-Dimanche' => '18h-01h']),
                'fourchette_prix' => '10000 - 30000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Villa+Kaya',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Lounge', 'Cocktails', 'Ambiance musicale']
            ],
            [
                'nom' => 'Chill N\ Grill',
                'ville_slug' => 'cotonou',
                'categorie_slug' => 'restaurants',
                'description' => 'Endroit parfait pour se détendre et savourer de bonnes grillades.',
                'adresse' => 'Cadjehoun, Cotonou',
                'telephone' => '+229 21 30 12 51',
                'whatsapp' => '+229 97 00 00 17',
                'email' => 'contact@chillngrill.com',
                'site_web' => 'https://www.chillngrill.com',
                'latitude' => 6.356000,
                'longitude' => 2.381000,
                'horaires' => json_encode(['Lundi-Dimanche' => '12h-23h']),
                'fourchette_prix' => '5000 - 15000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Chill+N+Grill',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Grillades', 'Terrasse', 'Ambiance décontractée']
            ],
            [
                'nom' => 'Maquis du Port',
                'ville_slug' => 'cotonou',
                'categorie_slug' => 'restaurants',
                'description' => 'Cuisine locale et ambiance conviviale près du port.',
                'adresse' => 'Zone Portuaire, Cotonou',
                'telephone' => '+229 21 30 12 52',
                'whatsapp' => '+229 97 00 00 18',
                'email' => 'contact@maquisduport.com',
                'site_web' => 'https://www.maquisduport.com',
                'latitude' => 6.360000,
                'longitude' => 2.450000,
                'horaires' => json_encode(['Lundi-Samedi' => '08h-20h']),
                'fourchette_prix' => '3000 - 10000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Maquis+du+Port',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Cuisine locale', 'Ambiance conviviale', 'Repas rapides']
            ],
            [
                'nom' => 'Super Pili Pili',
                'ville_slug' => 'cotonou',
                'categorie_slug' => 'restaurants',
                'description' => 'Restaurant populaire pour ses plats épicés et savoureux.',
                'adresse' => 'Haie Vive, Cotonou',
                'telephone' => '+229 21 30 12 53',
                'whatsapp' => '+229 97 00 00 19',
                'email' => 'contact@superpilipili.com',
                'site_web' => 'https://www.superpilipili.com',
                'latitude' => 6.383000,
                'longitude' => 2.408000,
                'horaires' => json_encode(['Lundi-Dimanche' => '12h-23h']),
                'fourchette_prix' => '6000 - 18000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Super+Pili+Pili',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Plats épicés', 'Cuisine africaine', 'Terrasse']
            ],

            // Cotonou - Appartements Meublés
            [
                'nom' => 'Résidence Royale',
                'ville_slug' => 'cotonou',
                'categorie_slug' => 'appartements-meubles',
                'description' => 'Appartements meublés de standing avec services hôteliers.',
                'adresse' => 'Cadjehoun, Cotonou',
                'telephone' => '+229 21 30 12 54',
                'whatsapp' => '+229 97 00 00 20',
                'email' => 'contact@residenceroyale.com',
                'site_web' => 'https://www.residenceroyale.com',
                'latitude' => 6.357000,
                'longitude' => 2.382000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '25000 - 70000 FCFA/nuit',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Residence+Royale',
                'statut' => 'actif',
                'en_vedette' => true,
                'services' => ['Appartements équipés', 'Service de ménage', 'Sécurité 24/7']
            ],
            [
                'nom' => 'Appartements Akpakpa Le Bélier',
                'ville_slug' => 'cotonou',
                'categorie_slug' => 'appartements-meubles',
                'description' => 'Logements confortables et abordables à Akpakpa.',
                'adresse' => 'Akpakpa, Rue V sensad, Cotonou',
                'telephone' => '+229 21 30 12 55',
                'whatsapp' => '+229 97 00 00 21',
                'email' => 'contact@akpakpabelier.com',
                'site_web' => 'https://www.akpakpabelier.com',
                'latitude' => 6.376000,
                'longitude' => 2.451000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '15000 - 40000 FCFA/nuit',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Akpakpa+Belier',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Cuisine équipée', 'Climatisation', 'Parking']
            ],
            [
                'nom' => 'Résidence Marylène',
                'ville_slug' => 'cotonou',
                'categorie_slug' => 'appartements-meubles',
                'description' => 'Appartements modernes et bien situés à Haie Vive.',
                'adresse' => 'Haie Vive, Cotonou',
                'telephone' => '+229 21 30 12 56',
                'whatsapp' => '+229 97 00 00 22',
                'email' => 'contact@residencemarylene.com',
                'site_web' => 'https://www.residencemarylene.com',
                'latitude' => 6.384000,
                'longitude' => 2.409000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '30000 - 80000 FCFA/nuit',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Residence+Marylene',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Meublé', 'Climatisation', 'Gardiennage']
            ],
            [
                'nom' => 'Bamboo Numerik',
                'ville_slug' => 'cotonou',
                'categorie_slug' => 'appartements-meubles',
                'description' => 'Appartements connectés pour un séjour high-tech.',
                'adresse' => 'Fidjrossé, Cotonou',
                'telephone' => '+229 21 30 12 57',
                'whatsapp' => '+229 97 00 00 23',
                'email' => 'contact@bamboonumerik.com',
                'site_web' => 'https://www.bamboonumerik.com',
                'latitude' => 6.337000,
                'longitude' => 2.362000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '20000 - 60000 FCFA/nuit',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Bamboo+Numerik',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Smart TV', 'Internet haut débit', 'Cuisine moderne']
            ],
            [
                'nom' => 'Résidence Les Cocotiers',
                'ville_slug' => 'cotonou',
                'categorie_slug' => 'appartements-meubles',
                'description' => 'Appartements spacieux dans un quartier calme.',
                'adresse' => 'Les Cocotiers, Cotonou',
                'telephone' => '+229 21 30 12 58',
                'whatsapp' => '+229 97 00 00 24',
                'email' => 'contact@residencecocotiers.com',
                'site_web' => 'https://www.residencecocotiers.com',
                'latitude' => 6.372000,
                'longitude' => 2.402000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '28000 - 75000 FCFA/nuit',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Residence+Cocotiers',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Grand salon', 'Balcon', 'Proche commodités']
            ],
            [
                'nom' => 'Appartement Fidjrossé Plage',
                'ville_slug' => 'cotonou',
                'categorie_slug' => 'appartements-meubles',
                'description' => 'Appartement avec accès direct à la plage.',
                'adresse' => 'Fidjrossé, Cotonou',
                'telephone' => '+229 21 30 12 59',
                'whatsapp' => '+229 97 00 00 25',
                'email' => 'contact@fidjrosseplage.com',
                'site_web' => 'https://www.fidjrosseplage.com',
                'latitude' => 6.338000,
                'longitude' => 2.363000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '35000 - 90000 FCFA/nuit',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Fidjrosse+Plage',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Vue sur mer', 'Accès plage', 'Cuisine équipée']
            ],
            [
                'nom' => 'Résidence Ganhi',
                'ville_slug' => 'cotonou',
                'categorie_slug' => 'appartements-meubles',
                'description' => 'Appartements en plein centre-ville, idéal pour les affaires.',
                'adresse' => 'Ganhi, Cotonou',
                'telephone' => '+229 21 30 12 60',
                'whatsapp' => '+229 97 00 00 26',
                'email' => 'contact@residenceganhi.com',
                'site_web' => 'https://www.residenceganhi.com',
                'latitude' => 6.361000,
                'longitude' => 2.421000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '22000 - 65000 FCFA/nuit',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Residence+Ganhi',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Centre-ville', 'Climatisation', 'Internet']
            ],
            [
                'nom' => 'Studio Meublé Cadjehoun',
                'ville_slug' => 'cotonou',
                'categorie_slug' => 'appartements-meubles',
                'description' => 'Studio confortable et fonctionnel à Cadjehoun.',
                'adresse' => 'Cadjehoun, Cotonou',
                'telephone' => '+229 21 30 12 61',
                'whatsapp' => '+229 97 00 00 27',
                'email' => 'contact@studiocadjehoun.com',
                'site_web' => 'https://www.studiocadjehoun.com',
                'latitude' => 6.358000,
                'longitude' => 2.383000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '18000 - 45000 FCFA/nuit',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Studio+Cadjehoun',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Cuisine', 'Climatisation', 'TV']
            ],
            [
                'nom' => 'Appartement de Luxe Haie Vive',
                'ville_slug' => 'cotonou',
                'categorie_slug' => 'appartements-meubles',
                'description' => 'Appartement haut de gamme avec toutes les commodités.',
                'adresse' => 'Haie Vive, Cotonou',
                'telephone' => '+229 21 30 12 62',
                'whatsapp' => '+229 97 00 00 28',
                'email' => 'contact@luxhaievive.com',
                'site_web' => 'https://www.luxhaievive.com',
                'latitude' => 6.385000,
                'longitude' => 2.410000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '40000 - 100000 FCFA/nuit',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Appart+Luxe+Haie+Vive',
                'statut' => 'actif',
                'en_vedette' => true,
                'services' => ['Piscine', 'Salle de sport', 'Vue panoramique']
            ],
            [
                'nom' => 'Résidence Calavi Centre',
                'ville_slug' => 'cotonou',
                'categorie_slug' => 'appartements-meubles',
                'description' => 'Appartements modernes et spacieux à Abomey-Calavi.',
                'adresse' => 'Abomey-Calavi, Cotonou',
                'telephone' => '+229 21 30 12 63',
                'whatsapp' => '+229 97 00 00 29',
                'email' => 'contact@residencecalavi.com',
                'site_web' => 'https://www.residencecalavi.com',
                'latitude' => 6.440000,
                'longitude' => 2.350000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '20000 - 55000 FCFA/nuit',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Residence+Calavi',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Proche université', 'Climatisation', 'Parking']
            ],

            // Bohicon/Abomey - Hôtels
            [
                'nom' => 'Reine Hotel',
                'ville_slug' => 'bohicon-abomey',
                'categorie_slug' => 'hotels',
                'description' => 'Hôtel confortable et bien situé à Bohicon.',
                'adresse' => 'Bohicon, Bénin',
                'telephone' => '+229 22 41 00 00',
                'whatsapp' => '+229 97 00 00 30',
                'email' => 'contact@reinehotel.com',
                'site_web' => 'https://www.reinehotel.com',
                'latitude' => 7.166667,
                'longitude' => 1.983333,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '20000 - 50000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Reine+Hotel',
                'statut' => 'actif',
                'en_vedette' => true,
                'services' => ['Wifi', 'Restaurant', 'Climatisation']
            ],
            [
                'nom' => 'Villa ETE-D',
                'ville_slug' => 'bohicon-abomey',
                'categorie_slug' => 'hotels',
                'description' => 'Villa avec piscine pour un séjour relaxant.',
                'adresse' => 'Bohicon, Bénin',
                'telephone' => '+229 22 41 00 01',
                'whatsapp' => '+229 97 00 00 31',
                'email' => 'contact@villaeted.com',
                'site_web' => 'https://www.villaeted.com',
                'latitude' => 7.170000,
                'longitude' => 1.985000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '30000 - 70000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Villa+ETE-D',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Piscine', 'Jardin', 'Calme']
            ],
            [
                'nom' => 'Hôtel La Majesté',
                'ville_slug' => 'bohicon-abomey',
                'categorie_slug' => 'hotels',
                'description' => 'Hôtel élégant avec des chambres spacieuses.',
                'adresse' => 'Bohicon, Bénin',
                'telephone' => '+229 22 41 00 02',
                'whatsapp' => '+229 97 00 00 32',
                'email' => 'contact@lamajeste.com',
                'site_web' => 'https://www.lamajeste.com',
                'latitude' => 7.165000,
                'longitude' => 1.980000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '25000 - 60000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Hotel+La+Majeste',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Restaurant', 'Bar', 'Salle de conférence']
            ],
            [
                'nom' => 'Bois Vert Hôtel',
                'ville_slug' => 'bohicon-abomey',
                'categorie_slug' => 'hotels',
                'description' => 'Hôtel au cœur de la nature à Abomey.',
                'adresse' => 'Abomey, Bénin',
                'telephone' => '+229 22 50 00 00',
                'whatsapp' => '+229 97 00 00 33',
                'email' => 'contact@boisverthotel.com',
                'site_web' => 'https://www.boisverthotel.com',
                'latitude' => 7.180000,
                'longitude' => 1.990000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '22000 - 55000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Bois+Vert+Hotel',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Jardin', 'Restaurant', 'Calme']
            ],
            [
                'nom' => 'Hôtel Jeco',
                'ville_slug' => 'bohicon-abomey',
                'categorie_slug' => 'hotels',
                'description' => 'Hôtel moderne avec un excellent service client.',
                'adresse' => 'Abomey, Bénin',
                'telephone' => '+229 22 50 00 01',
                'whatsapp' => '+229 97 00 00 34',
                'email' => 'contact@hoteljeco.com',
                'site_web' => 'https://www.hoteljeco.com',
                'latitude' => 7.181000,
                'longitude' => 1.991000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '28000 - 65000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Hotel+Jeco',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Wifi', 'Restaurant', 'Climatisation']
            ],
            [
                'nom' => 'Hôtel Chez Monique',
                'ville_slug' => 'bohicon-abomey',
                'categorie_slug' => 'hotels',
                'description' => 'Hôtel familial avec une cuisine locale.',
                'adresse' => 'Abomey, Bénin',
                'telephone' => '+229 22 50 00 02',
                'whatsapp' => '+229 97 00 00 35',
                'email' => 'contact@chezmonique.com',
                'site_web' => 'https://www.chezmonique.com',
                'latitude' => 7.182000,
                'longitude' => 1.992000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '18000 - 45000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Hotel+Chez+Monique',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Cuisine locale', 'Ambiance familiale', 'Parking']
            ],
            [
                'nom' => 'Hôtel Sun City',
                'ville_slug' => 'bohicon-abomey',
                'categorie_slug' => 'hotels',
                'description' => 'Hôtel avec piscine et activités de loisirs.',
                'adresse' => 'Bohicon, Bénin',
                'telephone' => '+229 22 41 00 03',
                'whatsapp' => '+229 97 00 00 36',
                'email' => 'contact@suncityhotel.com',
                'site_web' => 'https://www.suncityhotel.com',
                'latitude' => 7.167000,
                'longitude' => 1.984000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '35000 - 80000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Hotel+Sun+City',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Piscine', 'Bar', 'Activités']
            ],
            [
                'nom' => 'Hôtel Le Gouverneur',
                'ville_slug' => 'bohicon-abomey',
                'categorie_slug' => 'hotels',
                'description' => 'Hôtel de prestige au cœur d\Abomey.',
                'adresse' => 'Abomey, Bénin',
                'telephone' => '+229 22 50 00 03',
                'whatsapp' => '+229 97 00 00 37',
                'email' => 'contact@legouverneur.com',
                'site_web' => 'https://www.legouverneur.com',
                'latitude' => 7.183000,
                'longitude' => 1.993000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '40000 - 90000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Hotel+Le+Gouverneur',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Luxe', 'Restaurant', 'Service en chambre']
            ],
            [
                'nom' => 'Hôtel Princesse',
                'ville_slug' => 'bohicon-abomey',
                'categorie_slug' => 'hotels',
                'description' => 'Hôtel charmant avec un excellent rapport qualité-prix.',
                'adresse' => 'Bohicon, Bénin',
                'telephone' => '+229 22 41 00 04',
                'whatsapp' => '+229 97 00 00 38',
                'email' => 'contact@hotelprincesse.com',
                'site_web' => 'https://www.hotelprincesse.com',
                'latitude' => 7.168000,
                'longitude' => 1.986000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '15000 - 35000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Hotel+Princesse',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Wifi', 'Climatisation', 'Petit déjeuner']
            ],
            [
                'nom' => 'Hôtel Dako',
                'ville_slug' => 'bohicon-abomey',
                'categorie_slug' => 'hotels',
                'description' => 'Hôtel simple et propre pour un séjour agréable.',
                'adresse' => 'Bohicon, Bénin',
                'telephone' => '+229 22 41 00 05',
                'whatsapp' => '+229 97 00 00 39',
                'email' => 'contact@hoteldako.com',
                'site_web' => 'https://www.hoteldako.com',
                'latitude' => 7.169000,
                'longitude' => 1.987000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '12000 - 30000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Hotel+Dako',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Wifi', 'TV', 'Eau chaude']
            ],

            // Bohicon/Abomey - Restaurants
            [
                'nom' => 'Magui Bar - Les Saveurs de Marguerite',
                'ville_slug' => 'bohicon-abomey',
                'categorie_slug' => 'restaurants',
                'description' => 'Cuisine africaine et européenne dans une ambiance conviviale.',
                'adresse' => 'Abomey, Bénin',
                'telephone' => '+229 22 50 00 04',
                'whatsapp' => '+229 97 00 00 40',
                'email' => 'contact@maguibar.com',
                'site_web' => 'https://www.maguibar.com',
                'latitude' => 7.184000,
                'longitude' => 1.994000,
                'horaires' => json_encode(['Lundi-Dimanche' => '10h-22h']),
                'fourchette_prix' => '5000 - 15000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Magui+Bar',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Cuisine locale', 'Bar', 'Terrasse']
            ],
            [
                'nom' => 'Restaurant Chez Dona Theoles',
                'ville_slug' => 'bohicon-abomey',
                'categorie_slug' => 'restaurants',
                'description' => 'Spécialités béninoises dans un cadre chaleureux.',
                'adresse' => 'Abomey, Bénin',
                'telephone' => '+229 22 50 00 05',
                'whatsapp' => '+229 97 00 00 41',
                'email' => 'contact@donatheoles.com',
                'site_web' => 'https://www.donatheoles.com',
                'latitude' => 7.185000,
                'longitude' => 1.995000,
                'horaires' => json_encode(['Mardi-Dimanche' => '11h-21h']),
                'fourchette_prix' => '4000 - 12000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Dona+Theoles',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Cuisine béninoise', 'Ambiance familiale', 'Prix abordables']
            ],
            [
                'nom' => 'Saveurs Royales',
                'ville_slug' => 'bohicon-abomey',
                'categorie_slug' => 'restaurants',
                'description' => 'Restaurant gastronomique avec des plats raffinés.',
                'adresse' => 'Bohicon, Bénin',
                'telephone' => '+229 22 41 00 06',
                'whatsapp' => '+229 97 00 00 42',
                'email' => 'contact@saveursroyales.com',
                'site_web' => 'https://www.saveursroyales.com',
                'latitude' => 7.171000,
                'longitude' => 1.988000,
                'horaires' => json_encode(['Mardi-Samedi' => '19h-23h']),
                'fourchette_prix' => '15000 - 35000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Saveurs+Royales',
                'statut' => 'actif',
                'en_vedette' => true,
                'services' => ['Cuisine raffinée', 'Vins', 'Cadre élégant']
            ],
            [
                'nom' => 'Terasses Rooftop',
                'ville_slug' => 'bohicon-abomey',
                'categorie_slug' => 'restaurants',
                'description' => 'Bar restaurant avec une vue panoramique sur Bohicon.',
                'adresse' => 'Bohicon, Bénin',
                'telephone' => '+229 22 41 00 07',
                'whatsapp' => '+229 97 00 00 43',
                'email' => 'contact@terassesrooftop.com',
                'site_web' => 'https://www.terassesrooftop.com',
                'latitude' => 7.172000,
                'longitude' => 1.989000,
                'horaires' => json_encode(['Lundi-Dimanche' => '17h-01h']),
                'fourchette_prix' => '8000 - 25000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Terasses+Rooftop',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Vue panoramique', 'Cocktails', 'Musique']
            ],
            [
                'nom' => 'Maquis Delphano',
                'ville_slug' => 'bohicon-abomey',
                'categorie_slug' => 'restaurants',
                'description' => 'Maquis populaire pour ses plats locaux et son ambiance.',
                'adresse' => 'Abomey, Bénin',
                'telephone' => '+229 22 50 00 06',
                'whatsapp' => '+229 97 00 00 44',
                'email' => 'contact@maquisdelphano.com',
                'site_web' => 'https://www.maquisdelphano.com',
                'latitude' => 7.186000,
                'longitude' => 1.996000,
                'horaires' => json_encode(['Lundi-Dimanche' => '09h-22h']),
                'fourchette_prix' => '3000 - 10000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Maquis+Delphano',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Cuisine locale', 'Ambiance décontractée', 'Bières']
            ],
            [
                'nom' => 'Restaurant Le Palais',
                'ville_slug' => 'bohicon-abomey',
                'categorie_slug' => 'restaurants',
                'description' => 'Restaurant élégant proposant une cuisine internationale.',
                'adresse' => 'Abomey, Bénin',
                'telephone' => '+229 22 50 00 07',
                'whatsapp' => '+229 97 00 00 45',
                'email' => 'contact@lepalais.com',
                'site_web' => 'https://www.lepalais.com',
                'latitude' => 7.187000,
                'longitude' => 1.997000,
                'horaires' => json_encode(['Mardi-Dimanche' => '12h-14h, 19h-22h']),
                'fourchette_prix' => '10000 - 25000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Restaurant+Le+Palais',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Cuisine internationale', 'Cadre raffiné', 'Service de qualité']
            ],
            [
                'nom' => 'Maquis Le Flamboyant',
                'ville_slug' => 'bohicon-abomey',
                'categorie_slug' => 'restaurants',
                'description' => 'Maquis animé avec musique live et plats locaux.',
                'adresse' => 'Bohicon, Bénin',
                'telephone' => '+229 22 41 00 08',
                'whatsapp' => '+229 97 00 00 46',
                'email' => 'contact@leflamboyant.com',
                'site_web' => 'https://www.leflamboyant.com',
                'latitude' => 7.173000,
                'longitude' => 1.990000,
                'horaires' => json_encode(['Lundi-Dimanche' => '18h-02h']),
                'fourchette_prix' => '4000 - 15000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Maquis+Le+Flamboyant',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Musique live', 'Plats locaux', 'Ambiance festive']
            ],
            [
                'nom' => 'Restaurant La Paillote',
                'ville_slug' => 'bohicon-abomey',
                'categorie_slug' => 'restaurants',
                'description' => 'Restaurant en plein air avec des spécialités grillades.',
                'adresse' => 'Abomey, Bénin',
                'telephone' => '+229 22 50 00 08',
                'whatsapp' => '+229 97 00 00 47',
                'email' => 'contact@lapaillote.com',
                'site_web' => 'https://www.lapaillote.com',
                'latitude' => 7.188000,
                'longitude' => 1.998000,
                'horaires' => json_encode(['Lundi-Dimanche' => '12h-23h']),
                'fourchette_prix' => '6000 - 18000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Restaurant+La+Paillote',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Grillades', 'Terrasse', 'Cadre verdoyant']
            ],
            [
                'nom' => 'Maquis Chez Pierre',
                'ville_slug' => 'bohicon-abomey',
                'categorie_slug' => 'restaurants',
                'description' => 'Maquis traditionnel avec des plats copieux.',
                'adresse' => 'Abomey, Bénin',
                'telephone' => '+229 22 50 00 09',
                'whatsapp' => '+229 97 00 00 48',
                'email' => 'contact@chezpierre.com',
                'site_web' => 'https://www.chezpierre.com',
                'latitude' => 7.189000,
                'longitude' => 1.999000,
                'horaires' => json_encode(['Lundi-Dimanche' => '08h-20h']),
                'fourchette_prix' => '3000 - 8000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Maquis+Chez+Pierre',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Plats traditionnels', 'Ambiance locale', 'Prix bas']
            ],
            [
                'nom' => 'Restaurant Carrefour Mokas',
                'ville_slug' => 'bohicon-abomey',
                'categorie_slug' => 'restaurants',
                'description' => 'Restaurant au carrefour Mokas, idéal pour une pause repas.',
                'adresse' => 'Carrefour Mokas, Bohicon, Bénin',
                'telephone' => '+229 22 41 00 09',
                'whatsapp' => '+229 97 00 00 49',
                'email' => 'contact@carrefourmokas.com',
                'site_web' => 'https://www.carrefourmokas.com',
                'latitude' => 7.174000,
                'longitude' => 1.991000,
                'horaires' => json_encode(['Lundi-Dimanche' => '07h-22h']),
                'fourchette_prix' => '2000 - 7000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Carrefour+Mokas',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Repas rapides', 'Café', 'Boissons']
            ],

            // Bohicon/Abomey - Appartements Meublés
            [
                'nom' => 'Résidence Merry Home',
                'ville_slug' => 'bohicon-abomey',
                'categorie_slug' => 'appartements-meubles',
                'description' => 'Appartements confortables pour un séjour comme à la maison.',
                'adresse' => 'Abomey, Bénin',
                'telephone' => '+229 22 50 00 10',
                'whatsapp' => '+229 97 00 00 50',
                'email' => 'contact@merryhome.com',
                'site_web' => 'https://www.merryhome.com',
                'latitude' => 7.190000,
                'longitude' => 2.000000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '15000 - 40000 FCFA/nuit',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Merry+Home',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Cuisine équipée', 'Climatisation', 'TV']
            ],
            [
                'nom' => 'Appartement Meublé Bohicon Centre',
                'ville_slug' => 'bohicon-abomey',
                'categorie_slug' => 'appartements-meubles',
                'description' => 'Appartement moderne en plein centre de Bohicon.',
                'adresse' => 'Bohicon Centre, Bénin',
                'telephone' => '+229 22 41 00 10',
                'whatsapp' => '+229 97 00 00 51',
                'email' => 'contact@bohiconcentre.com',
                'site_web' => 'https://www.bohiconcentre.com',
                'latitude' => 7.175000,
                'longitude' => 1.992000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '18000 - 45000 FCFA/nuit',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Appart+Bohicon+Centre',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Proche commerces', 'Climatisation', 'Internet']
            ],
            [
                'nom' => 'Résidence Tindji',
                'ville_slug' => 'bohicon-abomey',
                'categorie_slug' => 'appartements-meubles',
                'description' => 'Appartements calmes et sécurisés à Tindji.',
                'adresse' => 'Tindji, Bohicon, Bénin',
                'telephone' => '+229 22 41 00 11',
                'whatsapp' => '+229 97 00 00 52',
                'email' => 'contact@residencetindji.com',
                'site_web' => 'https://www.residencetindji.com',
                'latitude' => 7.176000,
                'longitude' => 1.993000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '20000 - 50000 FCFA/nuit',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Residence+Tindji',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Sécurité', 'Jardin', 'Cuisine équipée']
            ],
            [
                'nom' => 'Studio Meublé Abomey',
                'ville_slug' => 'bohicon-abomey',
                'categorie_slug' => 'appartements-meubles',
                'description' => 'Studio fonctionnel et bien agencé à Abomey.',
                'adresse' => 'Abomey, Bénin',
                'telephone' => '+229 22 50 00 11',
                'whatsapp' => '+229 97 00 00 53',
                'email' => 'contact@studioabomey.com',
                'site_web' => 'https://www.studioabomey.com',
                'latitude' => 7.191000,
                'longitude' => 2.001000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '12000 - 30000 FCFA/nuit',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Studio+Abomey',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Cuisine', 'Climatisation', 'TV']
            ],
            [
                'nom' => 'Appartement de Luxe Bohicon',
                'ville_slug' => 'bohicon-abomey',
                'categorie_slug' => 'appartements-meubles',
                'description' => 'Appartement de luxe avec des prestations haut de gamme.',
                'adresse' => 'Bohicon, Bénin',
                'telephone' => '+229 22 41 00 12',
                'whatsapp' => '+229 97 00 00 54',
                'email' => 'contact@luxebohicon.com',
                'site_web' => 'https://www.luxebohicon.com',
                'latitude' => 7.177000,
                'longitude' => 1.994000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '30000 - 80000 FCFA/nuit',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Appart+Luxe+Bohicon',
                'statut' => 'actif',
                'en_vedette' => true,
                'services' => ['Piscine', 'Salle de sport', 'Vue panoramique']
            ],
            [
                'nom' => 'Résidence Historique Abomey',
                'ville_slug' => 'bohicon-abomey',
                'categorie_slug' => 'appartements-meubles',
                'description' => 'Appartements meublés à proximité des sites historiques.',
                'adresse' => 'Abomey, Bénin',
                'telephone' => '+229 22 50 00 12',
                'whatsapp' => '+229 97 00 00 55',
                'email' => 'contact@residencehistorique.com',
                'site_web' => 'https://www.residencehistorique.com',
                'latitude' => 7.192000,
                'longitude' => 2.002000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '25000 - 60000 FCFA/nuit',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Residence+Historique',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Proche musée', 'Climatisation', 'Parking']
            ],
            [
                'nom' => 'Appartement Calavi Centre (Bohicon/Abomey)',
                'ville_slug' => 'bohicon-abomey',
                'categorie_slug' => 'appartements-meubles',
                'description' => 'Appartements modernes et spacieux à Abomey-Calavi.',
                'adresse' => 'Abomey-Calavi, Bénin',
                'telephone' => '+229 22 41 00 13',
                'whatsapp' => '+229 97 00 00 56',
                'email' => 'contact@calavicentre.com',
                'site_web' => 'https://www.calavicentre.com',
                'latitude' => 6.441000,
                'longitude' => 2.351000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '20000 - 55000 FCFA/nuit',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Appart+Calavi+Centre',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Proche université', 'Climatisation', 'Parking']
            ],
            [
                'nom' => 'Gîte Rural Abomey',
                'ville_slug' => 'bohicon-abomey',
                'categorie_slug' => 'appartements-meubles',
                'description' => 'Gîte charmant pour une immersion rurale.',
                'adresse' => 'Abomey, Bénin',
                'telephone' => '+229 22 50 00 13',
                'whatsapp' => '+229 97 00 00 57',
                'email' => 'contact@giteruralabomey.com',
                'site_web' => 'https://www.giteruralabomey.com',
                'latitude' => 7.193000,
                'longitude' => 2.003000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '10000 - 25000 FCFA/nuit',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Gite+Rural+Abomey',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Calme', 'Nature', 'Cuisine locale']
            ],
            [
                'nom' => 'Résidence Mokas',
                'ville_slug' => 'bohicon-abomey',
                'categorie_slug' => 'appartements-meubles',
                'description' => 'Appartements modernes et bien équipés près du carrefour Mokas.',
                'adresse' => 'Carrefour Mokas, Bohicon, Bénin',
                'telephone' => '+229 22 41 00 14',
                'whatsapp' => '+229 97 00 00 58',
                'email' => 'contact@residencemokas.com',
                'site_web' => 'https://www.residencemokas.com',
                'latitude' => 7.178000,
                'longitude' => 1.995000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '18000 - 45000 FCFA/nuit',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Residence+Mokas',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Proche commerces', 'Climatisation', 'Internet']
            ],
            [
                'nom' => 'Appartement Proche Musée Abomey',
                'ville_slug' => 'bohicon-abomey',
                'categorie_slug' => 'appartements-meubles',
                'description' => 'Appartement idéal pour visiter le musée d\Abomey.',
                'adresse' => 'Abomey, Bénin',
                'telephone' => '+229 22 50 00 14',
                'whatsapp' => '+229 97 00 00 59',
                'email' => 'contact@appartmuseeabomey.com',
                'site_web' => 'https://www.appartmuseeabomey.com',
                'latitude' => 7.194000,
                'longitude' => 2.004000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '20000 - 50000 FCFA/nuit',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Appart+Musee+Abomey',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Proche musée', 'Cuisine équipée', 'Climatisation']
            ],

            // Parakou - Hôtels
            [
                'nom' => 'Benin Metropole Hotel',
                'ville_slug' => 'parakou',
                'categorie_slug' => 'hotels',
                'description' => 'Hôtel de luxe avec des services haut de gamme.',
                'adresse' => 'Parakou, Bénin',
                'telephone' => '+229 23 61 00 00',
                'whatsapp' => '+229 97 00 00 60',
                'email' => 'contact@beninmetropole.com',
                'site_web' => 'https://www.beninmetropole.com',
                'latitude' => 9.350000,
                'longitude' => 2.633333,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '40000 - 120000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Benin+Metropole+Hotel',
                'statut' => 'actif',
                'en_vedette' => true,
                'services' => ['Piscine', 'Restaurant', 'Salle de conférence']
            ],
            [
                'nom' => 'Hotel Kinyao',
                'ville_slug' => 'parakou',
                'categorie_slug' => 'hotels',
                'description' => 'Hôtel moderne et confortable au cœur de Parakou.',
                'adresse' => 'Parakou, Bénin',
                'telephone' => '+229 23 61 00 01',
                'whatsapp' => '+229 97 00 00 61',
                'email' => 'contact@hotelkinyao.com',
                'site_web' => 'https://www.hotelkinyao.com',
                'latitude' => 9.351000,
                'longitude' => 2.634000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '30000 - 80000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Hotel+Kinyao',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Wifi', 'Climatisation', 'Restaurant']
            ],
            [
                'nom' => 'Feel Well Guest House',
                'ville_slug' => 'parakou',
                'categorie_slug' => 'hotels',
                'description' => 'Maison d\hôtes accueillante avec un excellent service.',
                'adresse' => 'Parakou, Bénin',
                'telephone' => '+229 23 61 00 02',
                'whatsapp' => '+229 97 00 00 62',
                'email' => 'contact@feelwell.com',
                'site_web' => 'https://www.feelwell.com',
                'latitude' => 9.352000,
                'longitude' => 2.635000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '20000 - 50000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Feel+Well+Guest+House',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Petit déjeuner', 'Jardin', 'Calme']
            ],
            [
                'nom' => 'Hôtel Koburu City',
                'ville_slug' => 'parakou',
                'categorie_slug' => 'hotels',
                'description' => 'Hôtel central avec accès facile aux attractions de la ville.',
                'adresse' => 'Parakou, Bénin',
                'telephone' => '+229 23 61 00 03',
                'whatsapp' => '+229 97 00 00 63',
                'email' => 'contact@koburucity.com',
                'site_web' => 'https://www.koburucity.com',
                'latitude' => 9.353000,
                'longitude' => 2.636000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '25000 - 60000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Hotel+Koburu+City',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Proche centre-ville', 'Restaurant', 'Bar']
            ],
            [
                'nom' => 'Hôtel Les Routiers',
                'ville_slug' => 'parakou',
                'categorie_slug' => 'hotels',
                'description' => 'Hôtel pratique pour les voyageurs de passage.',
                'adresse' => 'Parakou, Bénin',
                'telephone' => '+229 23 61 00 04',
                'whatsapp' => '+229 97 00 00 64',
                'email' => 'contact@lesroutiers.com',
                'site_web' => 'https://www.lesroutiers.com',
                'latitude' => 9.354000,
                'longitude' => 2.637000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '15000 - 35000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Hotel+Les+Routiers',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Parking', 'Restaurant', 'Chambres simples']
            ],
            [
                'nom' => 'Hôtel La Résidence',
                'ville_slug' => 'parakou',
                'categorie_slug' => 'hotels',
                'description' => 'Hôtel calme et confortable pour un séjour reposant.',
                'adresse' => 'Parakou, Bénin',
                'telephone' => '+229 23 61 00 05',
                'whatsapp' => '+229 97 00 00 65',
                'email' => 'contact@laresidence.com',
                'site_web' => 'https://www.laresidence.com',
                'latitude' => 9.355000,
                'longitude' => 2.638000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '22000 - 55000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Hotel+La+Residence',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Jardin', 'Climatisation', 'TV']
            ],
            [
                'nom' => 'Hôtel Tichani',
                'ville_slug' => 'parakou',
                'categorie_slug' => 'hotels',
                'description' => 'Hôtel avec une architecture moderne et des services de qualité.',
                'adresse' => 'Parakou, Bénin',
                'telephone' => '+229 23 61 00 06',
                'whatsapp' => '+229 97 00 00 66',
                'email' => 'contact@hoteltichani.com',
                'site_web' => 'https://www.hoteltichani.com',
                'latitude' => 9.356000,
                'longitude' => 2.639000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '28000 - 70000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Hotel+Tichani',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Design moderne', 'Restaurant', 'Bar']
            ],
            [
                'nom' => 'Hôtel Princesse (Parakou)',
                'ville_slug' => 'parakou',
                'categorie_slug' => 'hotels',
                'description' => 'Hôtel charmant avec un excellent rapport qualité-prix.',
                'adresse' => 'Parakou, Bénin',
                'telephone' => '+229 23 61 00 07',
                'whatsapp' => '+229 97 00 00 67',
                'email' => 'contact@hotelprincesseparakou.com',
                'site_web' => 'https://www.hotelprincesseparakou.com',
                'latitude' => 9.357000,
                'longitude' => 2.640000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '18000 - 40000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Hotel+Princesse+Parakou',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Wifi', 'Climatisation', 'Petit déjeuner']
            ],
            [
                'nom' => 'Hôtel Borgou',
                'ville_slug' => 'parakou',
                'categorie_slug' => 'hotels',
                'description' => 'Hôtel emblématique de la région du Borgou.',
                'adresse' => 'Parakou, Bénin',
                'telephone' => '+229 23 61 00 08',
                'whatsapp' => '+229 97 00 00 68',
                'email' => 'contact@hotelborgou.com',
                'site_web' => 'https://www.hotelborgou.com',
                'latitude' => 9.358000,
                'longitude' => 2.641000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '30000 - 75000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Hotel+Borgou',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Histoire', 'Restaurant', 'Bar']
            ],
            [
                'nom' => 'Hôtel Alafia',
                'ville_slug' => 'parakou',
                'categorie_slug' => 'hotels',
                'description' => 'Hôtel paisible pour un séjour relaxant.',
                'adresse' => 'Parakou, Bénin',
                'telephone' => '+229 23 61 00 09',
                'whatsapp' => '+229 97 00 00 69',
                'email' => 'contact@hotelalafia.com',
                'site_web' => 'https://www.hotelalafia.com',
                'latitude' => 9.359000,
                'longitude' => 2.642000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '20000 - 50000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Hotel+Alafia',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Calme', 'Jardin', 'Restaurant']
            ],

            // Parakou - Restaurants
            [
                'nom' => 'Café Restaurant Nasuba Food',
                'ville_slug' => 'parakou',
                'categorie_slug' => 'restaurants',
                'description' => 'Restaurant avec une cuisine variée et un bon café.',
                'adresse' => 'Parakou, Bénin',
                'telephone' => '+229 23 61 00 10',
                'whatsapp' => '+229 97 00 00 70',
                'email' => 'contact@nasubafood.com',
                'site_web' => 'https://www.nasubafood.com',
                'latitude' => 9.360000,
                'longitude' => 2.643000,
                'horaires' => json_encode(['Lundi-Samedi' => '07h-22h']),
                'fourchette_prix' => '3000 - 10000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Nasuba+Food',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Café', 'Cuisine variée', 'Ambiance conviviale']
            ],
            [
                'nom' => 'Terrano Food',
                'ville_slug' => 'parakou',
                'categorie_slug' => 'restaurants',
                'description' => 'Restaurant moderne avec des plats innovants.',
                'adresse' => 'Parakou, Bénin',
                'telephone' => '+229 23 61 00 11',
                'whatsapp' => '+229 97 00 00 71',
                'email' => 'contact@terranofood.com',
                'site_web' => 'https://www.terranofood.com',
                'latitude' => 9.361000,
                'longitude' => 2.644000,
                'horaires' => json_encode(['Mardi-Dimanche' => '12h-14h30, 19h-22h30']),
                'fourchette_prix' => '8000 - 20000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Terrano+Food',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Cuisine inventive', 'Design moderne', 'Service rapide']
            ],
            [
                'nom' => 'Le Secret de la Vieille Marmite',
                'ville_slug' => 'parakou',
                'categorie_slug' => 'restaurants',
                'description' => 'Cuisine traditionnelle béninoise avec des recettes ancestrales.',
                'adresse' => 'Parakou, Bénin',
                'telephone' => '+229 23 61 00 12',
                'whatsapp' => '+229 97 00 00 72',
                'email' => 'contact@vieillemarmite.com',
                'site_web' => 'https://www.vieillemarmite.com',
                'latitude' => 9.362000,
                'longitude' => 2.645000,
                'horaires' => json_encode(['Lundi-Samedi' => '11h-21h']),
                'fourchette_prix' => '5000 - 15000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Vieille+Marmite',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Cuisine traditionnelle', 'Ambiance locale', 'Plats copieux']
            ],
            [
                'nom' => 'Cave du Nord',
                'ville_slug' => 'parakou',
                'categorie_slug' => 'restaurants',
                'description' => 'Bar à vin et restaurant avec une sélection de plats.',
                'adresse' => 'Parakou, Bénin',
                'telephone' => '+229 23 61 00 13',
                'whatsapp' => '+229 97 00 00 73',
                'email' => 'contact@cavedunord.com',
                'site_web' => 'https://www.cavedunord.com',
                'latitude' => 9.363000,
                'longitude' => 2.646000,
                'horaires' => json_encode(['Mardi-Dimanche' => '18h-00h']),
                'fourchette_prix' => '10000 - 25000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Cave+du+Nord',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Vins', 'Plats européens', 'Ambiance cosy']
            ],
            [
                'nom' => 'Himalaya Bar Restaurant',
                'ville_slug' => 'parakou',
                'categorie_slug' => 'restaurants',
                'description' => 'Restaurant avec des spécialités indiennes et asiatiques.',
                'adresse' => 'Parakou, Bénin',
                'telephone' => '+229 23 61 00 14',
                'whatsapp' => '+229 97 00 00 74',
                'email' => 'contact@himalayarestaurant.com',
                'site_web' => 'https://www.himalayarestaurant.com',
                'latitude' => 9.364000,
                'longitude' => 2.647000,
                'horaires' => json_encode(['Lundi-Dimanche' => '12h-14h, 19h-22h']),
                'fourchette_prix' => '7000 - 20000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Himalaya+Restaurant',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Cuisine indienne', 'Cuisine asiatique', 'Options végétariennes']
            ],
            [
                'nom' => 'Lounge Bar Chez Nabil',
                'ville_slug' => 'parakou',
                'categorie_slug' => 'restaurants',
                'description' => 'Lounge bar avec des cocktails et des tapas.',
                'adresse' => 'Parakou, Bénin',
                'telephone' => '+229 23 61 00 15',
                'whatsapp' => '+229 97 00 00 75',
                'email' => 'contact@cheznabil.com',
                'site_web' => 'https://www.cheznabil.com',
                'latitude' => 9.365000,
                'longitude' => 2.648000,
                'horaires' => json_encode(['Mardi-Dimanche' => '18h-02h']),
                'fourchette_prix' => '5000 - 15000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Chez+Nabil',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Cocktails', 'Tapas', 'Ambiance lounge']
            ],
            [
                'nom' => 'Maquis de A à Z FIESTA',
                'ville_slug' => 'parakou',
                'categorie_slug' => 'restaurants',
                'description' => 'Maquis festif avec musique et plats locaux.',
                'adresse' => 'Parakou, Bénin',
                'telephone' => '+229 23 61 00 16',
                'whatsapp' => '+229 97 00 00 76',
                'email' => 'contact@fiesta.com',
                'site_web' => 'https://www.fiesta.com',
                'latitude' => 9.366000,
                'longitude' => 2.649000,
                'horaires' => json_encode(['Lundi-Dimanche' => '18h-03h']),
                'fourchette_prix' => '4000 - 12000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Fiesta',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Musique', 'Plats locaux', 'Ambiance festive']
            ],
            [
                'nom' => 'Pink Paradise',
                'ville_slug' => 'parakou',
                'categorie_slug' => 'restaurants',
                'description' => 'Restaurant et bar avec une décoration unique.',
                'adresse' => 'Parakou, Bénin',
                'telephone' => '+229 23 61 00 17',
                'whatsapp' => '+229 97 00 00 77',
                'email' => 'contact@pinkparadise.com',
                'site_web' => 'https://www.pinkparadise.com',
                'latitude' => 9.367000,
                'longitude' => 2.650000,
                'horaires' => json_encode(['Mardi-Dimanche' => '12h-00h']),
                'fourchette_prix' => '6000 - 18000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Pink+Paradise',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Décoration', 'Cocktails', 'Cuisine internationale']
            ],
            [
                'nom' => 'La Cour des Grands',
                'ville_slug' => 'parakou',
                'categorie_slug' => 'restaurants',
                'description' => 'Restaurant haut de gamme avec une cuisine raffinée.',
                'adresse' => 'Parakou, Bénin',
                'telephone' => '+229 23 61 00 18',
                'whatsapp' => '+229 97 00 00 78',
                'email' => 'contact@lacourdesgrands.com',
                'site_web' => 'https://www.lacourdesgrands.com',
                'latitude' => 9.368000,
                'longitude' => 2.651000,
                'horaires' => json_encode(['Mardi-Samedi' => '19h-23h']),
                'fourchette_prix' => '12000 - 30000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=La+Cour+des+Grands',
                'statut' => 'actif',
                'en_vedette' => true,
                'services' => ['Cuisine gastronomique', 'Vins', 'Cadre élégant']
            ],
            [
                'nom' => 'Restaurant Le QuGey',
                'ville_slug' => 'parakou',
                'categorie_slug' => 'restaurants',
                'description' => 'Restaurant avec une cuisine variée et un bon service.',
                'adresse' => 'Parakou, Bénin',
                'telephone' => '+229 23 61 00 19',
                'whatsapp' => '+229 97 00 00 79',
                'email' => 'contact@lequgey.com',
                'site_web' => 'https://www.lequgey.com',
                'latitude' => 9.369000,
                'longitude' => 2.652000,
                'horaires' => json_encode(['Lundi-Dimanche' => '11h-22h']),
                'fourchette_prix' => '5000 - 15000 FCFA',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Le+QuGey',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Cuisine variée', 'Service rapide', 'Ambiance décontractée']
            ],

            // Parakou - Appartements Meublés
            [
                'nom' => 'Luxury Suites Parakou',
                'ville_slug' => 'parakou',
                'categorie_slug' => 'appartements-meubles',
                'description' => 'Appartements de luxe avec 3 chambres salon.',
                'adresse' => 'Parakou, Bénin',
                'telephone' => '+229 23 61 00 20',
                'whatsapp' => '+229 97 00 00 80',
                'email' => 'contact@luxurysuitesparakou.com',
                'site_web' => 'https://www.luxurysuitesparakou.com',
                'latitude' => 9.370000,
                'longitude' => 2.653000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '30000 - 80000 FCFA/nuit',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Luxury+Suites+Parakou',
                'statut' => 'actif',
                'en_vedette' => true,
                'services' => ['3 chambres', 'Salon', 'Cuisine équipée']
            ],
            [
                'nom' => 'Guest House Nol Palace',
                'ville_slug' => 'parakou',
                'categorie_slug' => 'appartements-meubles',
                'description' => 'Appartements meublés à Okedama, en face de l\HIA.',
                'adresse' => 'Quartier Okedama, Parakou, Bénin',
                'telephone' => '+229 23 61 00 21',
                'whatsapp' => '+229 97 00 00 81',
                'email' => 'contact@nolpalace.com',
                'site_web' => 'https://www.nolpalace.com',
                'latitude' => 9.371000,
                'longitude' => 2.654000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '10000 - 30000 FCFA/nuit',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Nol+Palace',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Studio', '1 chambre salon', '2 chambres salon']
            ],
            [
                'nom' => 'Appartement Meublé Okedama',
                'ville_slug' => 'parakou',
                'categorie_slug' => 'appartements-meubles',
                'description' => 'Appartements confortables et bien situés à Okedama.',
                'adresse' => 'Quartier Okedama, Parakou, Bénin',
                'telephone' => '+229 23 61 00 22',
                'whatsapp' => '+229 97 00 00 82',
                'email' => 'contact@okedamaappart.com',
                'site_web' => 'https://www.okedamaappart.com',
                'latitude' => 9.372000,
                'longitude' => 2.655000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '15000 - 40000 FCFA/nuit',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Appart+Okedama',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Cuisine équipée', 'Climatisation', 'Internet']
            ],
            [
                'nom' => 'Résidence Septentrion',
                'ville_slug' => 'parakou',
                'categorie_slug' => 'appartements-meubles',
                'description' => 'Appartements modernes et élégants dans le septentrion.',
                'adresse' => 'Parakou, Bénin',
                'telephone' => '+229 23 61 00 23',
                'whatsapp' => '+229 97 00 00 83',
                'email' => 'contact@residenceseptentrion.com',
                'site_web' => 'https://www.residenceseptentrion.com',
                'latitude' => 9.373000,
                'longitude' => 2.656000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '25000 - 70000 FCFA/nuit',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Residence+Septentrion',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Design moderne', 'Balcon', 'Vue sur la ville']
            ],
            [
                'nom' => 'Studio Meublé Parakou Centre',
                'ville_slug' => 'parakou',
                'categorie_slug' => 'appartements-meubles',
                'description' => 'Studio confortable et fonctionnel en plein centre de Parakou.',
                'adresse' => 'Parakou Centre, Bénin',
                'telephone' => '+229 23 61 00 24',
                'whatsapp' => '+229 97 00 00 84',
                'email' => 'contact@studioparakoucentre.com',
                'site_web' => 'https://www.studioparakoucentre.com',
                'latitude' => 9.374000,
                'longitude' => 2.657000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '12000 - 30000 FCFA/nuit',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Studio+Parakou+Centre',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Proche commerces', 'Climatisation', 'TV']
            ],
            [
                'nom' => 'Appartement Proche HIA Parakou',
                'ville_slug' => 'parakou',
                'categorie_slug' => 'appartements-meubles',
                'description' => 'Appartement idéalement situé près de l\Hôpital d\Instruction des Armées.',
                'adresse' => 'Parakou, Bénin',
                'telephone' => '+229 23 61 00 25',
                'whatsapp' => '+229 97 00 00 85',
                'email' => 'contact@apparthiaparakou.com',
                'site_web' => 'https://www.apparthiaparakou.com',
                'latitude' => 9.375000,
                'longitude' => 2.658000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '18000 - 45000 FCFA/nuit',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Appart+HIA+Parakou',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Proche hôpital', 'Cuisine équipée', 'Climatisation']
            ],
            [
                'nom' => 'Résidence Moderne Parakou',
                'ville_slug' => 'parakou',
                'categorie_slug' => 'appartements-meubles',
                'description' => 'Appartements avec un design moderne et des équipements récents.',
                'adresse' => 'Parakou, Bénin',
                'telephone' => '+229 23 61 00 26',
                'whatsapp' => '+229 97 00 00 86',
                'email' => 'contact@residencemoderneparakou.com',
                'site_web' => 'https://www.residencemoderneparakou.com',
                'latitude' => 9.376000,
                'longitude' => 2.659000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '22000 - 55000 FCFA/nuit',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Residence+Moderne+Parakou',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Design moderne', 'Internet', 'Parking sécurisé']
            ],
            [
                'nom' => 'Appartement 3 Chambres Salon Parakou',
                'ville_slug' => 'parakou',
                'categorie_slug' => 'appartements-meubles',
                'description' => 'Grand appartement familial avec 3 chambres et un salon spacieux.',
                'adresse' => 'Parakou, Bénin',
                'telephone' => '+229 23 61 00 27',
                'whatsapp' => '+229 97 00 00 87',
                'email' => 'contact@appart3chambresparakou.com',
                'site_web' => 'https://www.appart3chambresparakou.com',
                'latitude' => 9.377000,
                'longitude' => 2.660000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '35000 - 90000 FCFA/nuit',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Appart+3+Chambres+Parakou',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['3 chambres', 'Grand salon', 'Cuisine équipée']
            ],
            [
                'nom' => 'Guest House Parakou',
                'ville_slug' => 'parakou',
                'categorie_slug' => 'appartements-meubles',
                'description' => 'Maison d\hôtes avec des appartements meublés.',
                'adresse' => 'Parakou, Bénin',
                'telephone' => '+229 23 61 00 28',
                'whatsapp' => '+229 97 00 00 88',
                'email' => 'contact@guesthouseparakou.com',
                'site_web' => 'https://www.guesthouseparakou.com',
                'latitude' => 9.378000,
                'longitude' => 2.661000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '15000 - 40000 FCFA/nuit',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Guest+House+Parakou',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Confort', 'Calme', 'Service de ménage']
            ],
            [
                'nom' => 'Résidence Alafia Parakou',
                'ville_slug' => 'parakou',
                'categorie_slug' => 'appartements-meubles',
                'description' => 'Appartements paisibles pour un séjour agréable.',
                'adresse' => 'Parakou, Bénin',
                'telephone' => '+229 23 61 00 29',
                'whatsapp' => '+229 97 00 00 89',
                'email' => 'contact@residencealafiaparakou.com',
                'site_web' => 'https://www.residencealafiaparakou.com',
                'latitude' => 9.379000,
                'longitude' => 2.662000,
                'horaires' => json_encode(['Lundi-Dimanche' => '24/7']),
                'fourchette_prix' => '20000 - 50000 FCFA/nuit',
                'photo_principale' => 'https://via.placeholder.com/1024x768.png?text=Residence+Alafia+Parakou',
                'statut' => 'actif',
                'en_vedette' => false,
                'services' => ['Calme', 'Jardin', 'Cuisine équipée']
            ],
        ];

        foreach ($etablissementsData as $data) {
            $etablissement = Etablissement::create([
                'user_id' => $adminUser->id,
                'ville_id' => $villes[$data['ville_slug']]->id,
                'categorie_id' => $categories[$data['categorie_slug']]->id,
                'nom' => $data['nom'],
                'slug' => Str::slug($data['nom']),
                'description' => $data['description'],
                'adresse' => $data['adresse'],
                'telephone' => $data['telephone'] ?? null,
                'whatsapp' => $data['whatsapp'] ?? null,
                'email' => $data['email'] ?? null,
                'site_web' => $data['site_web'] ?? null,
                'latitude' => $data['latitude'] ?? null,
                'longitude' => $data['longitude'] ?? null,
                'horaires' => $data['horaires'] ?? null,
                'fourchette_prix' => $data['fourchette_prix'] ?? null,
                'photo_principale' => $data['photo_principale'] ?? null,
                'statut' => $data['statut'] ?? 'en_attente',
                'en_vedette' => $data['en_vedette'] ?? false,
            ]);

            // Ajout des photos (une seule photo principale pour l'instant)
            if (isset($data['photo_principale'])) {
                $etablissement->photos()->create([
                    'url' => $data['photo_principale'],
                    'legende' => 'Photo principale de ' . $data['nom'],
                    'ordre' => 0,
                ]);
            }

            // Ajout des services
            if (isset($data['services'])) {
                foreach ($data['services'] as $serviceLibelle) {
                    $etablissement->services()->create([
                        'libelle' => $serviceLibelle,
                        'emoji' => '✅', // Emoji par défaut
                    ]);
                }
            }
        }
    }
}
